# Generated by Django 3.2.18 on 2023-04-10 18:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('exp', models.IntegerField(default=100)),
                ('status', models.IntegerField(choices=[(0, 'User'), (1, 'Admin'), (2, 'Blocked')], default=0)),
                ('debank', models.CharField(blank=True, max_length=255)),
                ('avatar', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Testnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testnet_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='testnet_name', unique=True)),
                ('slug_original', models.CharField(max_length=60)),
                ('network_name', models.CharField(max_length=55)),
                ('network_status', models.CharField(max_length=25)),
                ('description', models.TextField(db_index=True)),
                ('category', models.CharField(max_length=35)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('discord', models.CharField(blank=True, max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('youtube', models.CharField(blank=True, max_length=255)),
                ('whitepaper', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=25)),
                ('tasks_description', models.TextField()),
                ('wallet1_name', models.CharField(blank=True, max_length=25)),
                ('wallet1_type', models.CharField(blank=True, max_length=25)),
                ('wallet1_link', models.CharField(blank=True, max_length=255)),
                ('wallet1_adress', models.CharField(blank=True, max_length=255)),
                ('wallet1_seed', models.CharField(blank=True, max_length=255)),
                ('wallet1_priv_key', models.CharField(blank=True, max_length=255)),
                ('wallet1_password', models.CharField(blank=True, max_length=30)),
                ('wallet1_session', models.CharField(blank=True, max_length=30)),
                ('wallet1_clue', models.TextField(blank=True)),
                ('wallet2_name', models.CharField(blank=True, max_length=25)),
                ('wallet2_type', models.CharField(blank=True, max_length=25)),
                ('wallet2_link', models.CharField(blank=True, max_length=255)),
                ('wallet2_adress', models.CharField(blank=True, max_length=255)),
                ('wallet2_seed', models.CharField(blank=True, max_length=255)),
                ('wallet2_priv_key', models.CharField(blank=True, max_length=255)),
                ('wallet2_password', models.CharField(blank=True, max_length=30)),
                ('wallet2_session', models.CharField(blank=True, max_length=30)),
                ('wallet2_clue', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('copied_nb', models.IntegerField(blank=True, default=0)),
                ('twitter_user', models.CharField(blank=True, max_length=21)),
                ('email_user', models.EmailField(blank=True, max_length=254)),
                ('website_user', models.CharField(blank=True, max_length=255)),
                ('github_user', models.CharField(blank=True, max_length=25)),
                ('discord_user', models.CharField(blank=True, max_length=25)),
                ('telegram_user', models.CharField(blank=True, max_length=25)),
                ('tasks_results', models.TextField(blank=True)),
                ('status_testnet', models.IntegerField(choices=[(0, 'published'), (2, 'Reported')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testnet_author', to=settings.AUTH_USER_MODEL)),
                ('testnet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testnet_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('read', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('notification_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('checklist_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
